### ISSUE TITLE
Perform parameter sweep on hardware and gather statistics

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#439]
We'd like to do a bunch of experiments to get a good feeling for clock control behavior in actual hardware. Ideally we'd sweep over a number of parameters:

 - Clock offsets
 - Topologies

To do this we need a number of things:

 - [ ] A way to do clock offsets in hardware
 - [ ] Topology configuration in hardware
 - [ ] A way to quickly execute a number of tests with different parameters

**Comment by lmbollen** [comment]
### Current HITL infrastructure
Set up test environment and check if required probes are present.
We currently assume that every FPGA contains the same bitstream and only check if the first FPGA has the required probes.
We collect the names of the start probes.
Since we can have multiple tests per bitstream we can have multiple start probes.
- For each start probe name:
  - For each device:
    - Initialize the device
    - Arm trigger and capture for each ILA
    - Set start probe
  - For each device:
    - Load & refresh the device
    - Wait for the test to end
    - Print the result
  - For each device:
    - Load & refresh the device
    - Load and store ILA data
  - Print the test summary

Finally, we print the summary of all tests.
Each test has a start, done and success probe.
### Proposed changes
#### Test stage control
We can still use a start probe for every independent test, but we can also do different tests in different stages. 

To create different stages in our test infrasctructure we add two probes: `num_stages` and `current_stage`.
Change the `done` probe and `success` probe into `stage_done`and `stage_fail`.
`num_stages` is controlled by the FPGA and represents the number of stages in the current test.
`current_stage` is controlled by Vivado and incremented every time `stage_done` is true.
If `current_stage == num_stages && stage_done` the test has succeeded.
#### Extra probe control
Each test can have a yaml file that contains stage information. In each stage we can assign new values to additional probe files, such as:
```yaml
stages:
  - name: reset
    index: 0
    probes:
    - devices:
      - index: 0
        link_mask: 0b0000_0001
        period_offset: 100
      - index: 1
        link_mask: 0b0000_0010
        period_offset: -100
  - name: setup
    index: 1
  - name: synchronize
    index: 2
  - name: apply period changes
    index: 3
  - name: synchronize
    index: 4

``` 
#### ILA control
For every stage, we arm the ILAs at the start, and check them at the end.
At the end we can extract the data if the ILA has been triggered, store it in a folder that corresponds to that stage and re-arm for the next stage.

**Comment by martijnbastiaan** [comment]
As discussed offline I think the stages can be handled by the FPGAs/tests themselves, like we do now.

```yaml
$start_probe_name:
  - $test_name:
    - index: $index
      config:
        $input_probe_name: $input_probe_value
```

where:

* `$start_probe_name`: refers to name of start probe
* `$test_name`: free form field, probably used to name the stored ILA data
* `$index`: FPGA to use, if left out implicitly counts from zero
* `$input_probe_name`: an input probe on the VIO with the start probe
* `$input_probe_value`: value to set input probe to before asserting start probe

I'm also wondering whether we could define this in Haskell, that way you could use native data types for the input probe values..

---------------------

Example:

```yaml
start_probe_a:
  - star:
    - index: 0
      config:
        link_mask: 0b0000_0001
        period_offset: 100
    - index: 1
      config:
        link_mask: 0b0000_0010
        period_offset: -100

# Empty dictionaries for auto inference
start_probe_b: {}
```
